pool: 'Default'

trigger:
- main

resources:
- repo: self

  
steps:
- script: |
    echo 'SonarCube running'
  displayName: SonarCube Scanning
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
     
- script: |
    sudo yarn 
  displayName: Install Dependence

- script: |
    yarn test
  displayName: Run Unit Test

- script: |
    yarn build
  displayName: Build

- script: |
    cp -r build/* /etc/nginx/html
  displayName: Deploy to UAT