pool: 'Default'

trigger:
- main
- releases/*

resources:
- repo: self

steps:
- script: |
    echo 'SonarCube running'
    displayName: SonarCube Scanning
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
      
- script: |
    sudo npm i  
  displayName: Install Dependence

- script: |
    sudo npm run test
  displayName: Run Unit Test

- script: |
    sudo npm run build
  displayName: Build

- script: |
    sudo cp -r dist/* /etc/nginx/html
  displayName: Deploy to UAT Environment
